package com.twc.bps.swebapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-05-29T10:13:56.825-04:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.twc.com/BPS/sWebAPI", name = "WebAPIServiceSoap")
@XmlSeeAlso({ObjectFactory.class, org.openuri._2002._04.soap.conversation.ObjectFactory.class, com.twc.bps.webservice.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebAPIServiceSoap {

    @WebMethod(action = "http://www.twc.com/BPS/sWebAPI/startAsyncRequest")
    @WebResult(name = "startAsyncRequestResponse", targetNamespace = "http://www.twc.com/BPS/sWebAPI", partName = "parameters")
    public StartAsyncRequestResponse startAsyncRequest(
        @WebParam(partName = "parameters", name = "startAsyncRequest", targetNamespace = "http://www.twc.com/BPS/sWebAPI")
        StartAsyncRequest parameters
    );

    @WebMethod(action = "http://www.twc.com/BPS/sWebAPI/request")
    @WebResult(name = "requestResponse", targetNamespace = "http://www.twc.com/BPS/sWebAPI", partName = "parameters")
    public RequestResponse request(
        @WebParam(partName = "parameters", name = "request", targetNamespace = "http://www.twc.com/BPS/sWebAPI")
        Request parameters
    );
}
