package com.twc.bps.swebapi;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-05-29T10:13:55.749-04:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.twc.com/BPS/sWebAPI", name = "WebAPIServiceSoapCallback")
@XmlSeeAlso({ObjectFactory.class, org.openuri._2002._04.soap.conversation.ObjectFactory.class, com.twc.bps.webservice.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebAPIServiceSoapCallback {

    @WebMethod(action = "http://www.twc.com/BPS/sWebAPI/requestResponse")
    @Oneway
    public void requestResponse(
        @WebParam(partName = "parameters", name = "requestResponse", targetNamespace = "http://www.twc.com/BPS/sWebAPI")
        RequestResponse parameters
    );
}
