package com.twc.bps.swebapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-05-29T10:13:56.835-04:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "WebAPIMediator_ep", 
                  wsdlLocation = "file:/C:/Users/Tmehta/Project/GIT/voice-portal-package/voice-portal-client/src/main/resources/GetVoicemailSettings.wsdl",
                  targetNamespace = "http://www.twc.com/BPS/sWebAPI") 
public class WebAPIMediatorEp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.twc.com/BPS/sWebAPI", "WebAPIMediator_ep");
    public final static QName WebAPIServiceSoapCallbackPt = new QName("http://www.twc.com/BPS/sWebAPI", "WebAPIServiceSoapCallback_pt");
    public final static QName WebAPIServiceSoapPt = new QName("http://www.twc.com/BPS/sWebAPI", "WebAPIServiceSoap_pt");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Tmehta/Project/GIT/voice-portal-package/voice-portal-client/src/main/resources/GetVoicemailSettings.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebAPIMediatorEp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Tmehta/Project/GIT/voice-portal-package/voice-portal-client/src/main/resources/GetVoicemailSettings.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebAPIMediatorEp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebAPIMediatorEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebAPIMediatorEp() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WebAPIMediatorEp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebAPIMediatorEp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebAPIMediatorEp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WebAPIServiceSoapCallback
     */
    @WebEndpoint(name = "WebAPIServiceSoapCallback_pt")
    public WebAPIServiceSoapCallback getWebAPIServiceSoapCallbackPt() {
        return super.getPort(WebAPIServiceSoapCallbackPt, WebAPIServiceSoapCallback.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebAPIServiceSoapCallback
     */
    @WebEndpoint(name = "WebAPIServiceSoapCallback_pt")
    public WebAPIServiceSoapCallback getWebAPIServiceSoapCallbackPt(WebServiceFeature... features) {
        return super.getPort(WebAPIServiceSoapCallbackPt, WebAPIServiceSoapCallback.class, features);
    }


    /**
     *
     * @return
     *     returns WebAPIServiceSoap
     */
    @WebEndpoint(name = "WebAPIServiceSoap_pt")
    public WebAPIServiceSoap getWebAPIServiceSoapPt() {
        return super.getPort(WebAPIServiceSoapPt, WebAPIServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebAPIServiceSoap
     */
    @WebEndpoint(name = "WebAPIServiceSoap_pt")
    public WebAPIServiceSoap getWebAPIServiceSoapPt(WebServiceFeature... features) {
        return super.getPort(WebAPIServiceSoapPt, WebAPIServiceSoap.class, features);
    }

}
